### ISSUE TITLE
Decompilation is not using pushed arguments for function call

### ISSUE THREAD

**Issue by iagocq** [revng/revng#455]
I am unable to get a correct decompilation for the following code:

```asm
; file: failing.asm

org 0x400000
bits 32
section .text

one_plus_two:
    push    2
    push    1
    call    sum

    ret

sum:
    mov     eax, [esp+4]
    add     eax, [esp+8]
    ret     8
```

I compiled it with `nasm -f bin -o failing.bin failing.asm`

I created a model.yml with the following content:

```yml
Architecture: x86
DefaultABI: Microsoft_x86_cdecl
Segments:
  - StartAddress: "0x400000:Generic32"
    VirtualSize: 21
    StartOffset: 0
    FileSize: 21
    IsReadable: true
    IsWriteable: false
    IsExecutable: true
Functions:
  - Entry: "0x400000:Code_x86"
    CustomName: one_plus_two
    Prototype:
      Kind: DefinedType
      Definition: "/TypeDefinitions/0-CABIFunctionDefinition"
  - Entry: "0x40000a:Code_x86"
    CustomName: sum
    Prototype:
      Kind: DefinedType
      Definition: "/TypeDefinitions/1-CABIFunctionDefinition"
TypeDefinitions:
  - Kind: CABIFunctionDefinition
    ABI: Microsoft_x86_cdecl
    ID: 0
    Arguments:
    ReturnType:
      Kind: PrimitiveType
      PrimitiveKind: Unsigned
      Size: 4
  - Kind: CABIFunctionDefinition
    ABI: Microsoft_x86_stdcall
    ID: 1
    Arguments:
      - Index: 0
        Type:
          Kind: PrimitiveType
          PrimitiveKind: Unsigned
          Size: 4
      - Index: 1
        Type:
          Kind: PrimitiveType
          PrimitiveKind: Unsigned
          Size: 4
    ReturnType:
      Kind: PrimitiveType
      PrimitiveKind: Unsigned
      Size: 4
```

I decompiled the code with `revng artifact --model model.yml decompile-to-single-file ./failing.bin | revng ptml > failing.c`. This is the resulting decompilation:

```c
#include "types-and-globals.h"
#include "helpers.h"

_ABI(Microsoft_x86_cdecl)
uint32_t one_plus_two(void) {
  uint32_t _var_0;
  *((generic32_t *) (__init_local_sp() - 4)) = 2;
  *((generic32_t *) (__init_local_sp() - 8)) = 1;
  _var_0 = sum(_undef_generic32_t(), _undef_generic32_t());
  return _var_0;
}

_ABI(Microsoft_x86_stdcall)
uint32_t sum(uint32_t argument_0, uint32_t argument_1) {
  uint32_t _var_0;
  uint32_t _var_1;
  _var_0 = argument_0;
  _var_1 = argument_1;
  return *((generic32_t *) ((number64_t) &_var_0 & 0xFFFFFFFC)) + *((generic32_t *) ((number64_t) &_var_1 & 0xFFFFFFFC));
}
```

For some reason, the arguments to the call to the sum function are incorrect. I expected sum(1, 2) instead of sum(_undef_generic32_t(), _undef_generic32_t()).

I am using rev.ng version 86edda9
