### ISSUE TITLE
UB when referring to the reserved stack space of a Microsoft_x86_64 function

### ISSUE THREAD

**Issue by iagocq** [revng/revng#456]
The Microsoft_x86_64 calling convention requires the caller to reserve enough stack space for the callee where all arguments can be stored.
The callee may use the top 32 bytes of the reserved space to save its register arguments, but it can also be used as a general purpose storage area that is always guaranteed to exist.
(source: https://learn.microsoft.com/en-us/cpp/build/stack-usage?view=msvc-170#stack-allocation)

This piece of code uses that reserved area when compiled with msvc with no optimizations:
```c
long long use_reserved_space(long long arg) {
    int a = 1;
    return arg;
}
```

and has this assembly:
```asm
use_reserved_space PROC
        mov     QWORD PTR [rsp+8], rcx
        sub     rsp, 24
        mov     DWORD PTR [rsp], 1
        mov     rax, QWORD PTR [rsp+32]
        add     rsp, 24
        ret     0
use_reserved_space ENDP
```

I then created a `model.yml` with the following contents:
```yml
Architecture: x86_64
DefaultABI: Microsoft_x86_64
Segments:
  - StartAddress: "0x400000:Generic64"
    VirtualSize: 28
    StartOffset: 0
    FileSize: 28
    IsReadable: true
    IsWriteable: false
    IsExecutable: true
Functions:
  - Entry: "0x400000:Code_x86_64"
    CustomName: push_into_reserved_space
    Prototype:
      Kind: DefinedType
      Definition: "/TypeDefinitions/0-CABIFunctionDefinition"
    StackFrameType:
      Kind: DefinedType
      Definition: "/TypeDefinitions/1-StructDefinition"
TypeDefinitions:
  - Kind: CABIFunctionDefinition
    ABI: Microsoft_x86_64
    ID: 0
    Arguments:
      - Index: 0
        Type:
          Kind: PrimitiveType
          PrimitiveKind: Unsigned
          Size: 4
    ReturnType:
      Kind: PrimitiveType
      PrimitiveKind: Unsigned
      Size: 8
  - Kind: StructDefinition
    ID: 1
    Size: 24
    Fields:
      - Offset: 0
        Type:
          Kind: PrimitiveType
          PrimitiveKind: Unsigned
          Size: 4
```

and decompiled the binary with `revng artifact --model model.yml decompile-to-single-file ./use-reserved-space.bin | revng ptml > use-reserved-space.c`, producing:

```c
#include "types-and-globals.h"
#include "helpers.h"

_ABI(Microsoft_x86_64)
uint64_t use_reserved_space(uint32_t argument_0) {
  struct _PACKED struct_1 {
    uint32_t offset_0;
    uint8_t padding_at_4[20];
  } _stack;
  *((generic64_t *) ((pointer_or_number64_t) &(&_stack)[1] + 8)) = argument_0;
  _stack.offset_0 = 1;
  return *((generic64_t *) ((pointer_or_number64_t) &(&_stack)[1] + 8));
}
```

The generated code uses undefined behavior to read and write to that area. It could use another approach such as accessing an explicitly reserved variable (some other local struct) that can grow according to the total number of parameters.
